version: '3.9'
services: 
    app:
        build: .
        depends_on: 
            - postgres
        ports:
             - "3001:3001"
        environment: 
            HOST: ${HOST}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
    postgres:
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
             - '5432:5432'
    ui:
        image: chronometer:1.2
        ports: 
            - "3000:80"
volumes:
    postgres: